---
name: release
on:
  release:
    types:
      - published

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  terraform-module:
    uses: cloudposse/.github/.github/workflows/shared-release-branches.yml@main
    secrets: inherit
